### ISSUE TITLE
Bug in Java version

### ISSUE THREAD

**Issue by romancardenas** [iscar-ucm/xdevs#1]
I found a bug in `java/src/xdevs/modeling/Atomic.java`:
https://github.com/jlrisco/xdevs/blob/da45c28c0ed6cb92d5d1f93e96c51686f041d94b/java/src/xdevs/core/modeling/Atomic.java#L97

shouldn't it be `deltext(e)`?

**Comment by jlrisco** [comment]
No, according to DEVS, deltcon is defined in terms of S and X, i.e., deltcon: SxXb->S. There is no elapsed time here. The bug is in the simulator, this sentence must be removed:
model.setSigma(model.getSigma() - e);

I am doing that.
